AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for Spring Boot application deployed to AWS Lambda
  with API Gateway and SSM Parameter Store integration.

Globals:
  Function:
    Timeout: 20
    MemorySize: 1024
    Architectures:
      - x86_64

Resources:
  SpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.tsix_hack.spam_ai_detection.StreamLambdaHandler::handleRequest  # Corrigé le double point "::"
      Runtime: java21
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY


Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  LambdaFunction:
    Description: "Spring Boot Lambda Function ARN"
    Value: !GetAtt SpringBootFunction.Arn
  LambdaRole:
    Description: "IAM Role used by the Lambda function"
    Value: !GetAtt SpringBootFunctionRole.Arn
